// DO NOT EDIT THIS FILE. ALL CHANGES WILL BE ERASED WHEN THIS FILE IS REGENERATED

#include <stdbool.h>
#include "jthread.h"

static const char *instr_names[256] = {
	"nop",
	"aconst_null",
	"iconst_m1",
	"iconst_0",
	"iconst_1",
	"iconst_2",
	"iconst_3",
	"iconst_4",
	"iconst_5",
	"lconst_0",
	"lconst_1",
	"fconst_0",
	"fconst_1",
	"fconst_2",
	"dconst_0",
	"dconst_1",
	"bipush",
	"sipush",
	"ldc",
	"ldc_w",
	"ldc2_w",
	"iload",
	"lload",
	"fload",
	"dload",
	"aload",
	"iload_0",
	"iload_1",
	"iload_2",
	"iload_3",
	"lload_0",
	"lload_1",
	"lload_2",
	"lload_3",
	"fload_0",
	"fload_1",
	"fload_2",
	"fload_3",
	"dload_0",
	"dload_1",
	"dload_2",
	"dload_3",
	"aload_0",
	"aload_1",
	"aload_2",
	"aload_3",
	"iaload",
	"laload",
	"faload",
	"daload",
	"aaload",
	"baload",
	"caload",
	"saload",
	"istore",
	"lstore",
	"fstore",
	"dstore",
	"astore",
	"istore_0",
	"istore_1",
	"istore_2",
	"istore_3",
	"lstore_0",
	"lstore_1",
	"lstore_2",
	"lstore_3",
	"fstore_0",
	"fstore_1",
	"fstore_2",
	"fstore_3",
	"dstore_0",
	"dstore_1",
	"dstore_2",
	"dstore_3",
	"astore_0",
	"astore_1",
	"astore_2",
	"astore_3",
	"iastore",
	"lastore",
	"fastore",
	"dastore",
	"aastore",
	"bastore",
	"castore",
	"sastore",
	"pop",
	"pop2",
	"dup",
	"dup_x1",
	"dup_x2",
	"dup2",
	"dup2_x1",
	"dup2_x2",
	"swap",
	"iadd",
	"ladd",
	"fadd",
	"dadd",
	"isub",
	"lsub",
	"fsub",
	"dsub",
	"imul",
	"lmul",
	"fmul",
	"dmul",
	"idiv",
	"ldiv",
	"fdiv",
	"ddiv",
	"irem",
	"lrem",
	"frem",
	"drem",
	"ineg",
	"lneg",
	"fneg",
	"dneg",
	"ishl",
	"lshl",
	"ishr",
	"lshr",
	"iushr",
	"lushr",
	"iand",
	"land",
	"ior",
	"lor",
	"ixor",
	"lxor",
	"iinc",
	"i2l",
	"i2f",
	"i2d",
	"l2i",
	"l2f",
	"l2d",
	"f2i",
	"f2l",
	"f2d",
	"d2i",
	"d2l",
	"d2f",
	"i2b",
	"i2c",
	"i2s",
	"lcmp",
	"fcmpl",
	"fcmpg",
	"dcmpl",
	"dcmpg",
	"ifeq",
	"ifne",
	"iflt",
	"ifge",
	"ifgt",
	"ifle",
	"if_icmpeq",
	"if_icmpne",
	"if_icmplt",
	"if_icmpge",
	"if_icmpgt",
	"if_icmple",
	"if_acmpeq",
	"if_acmpne",
	"goto",
	"jsr",
	"ret",
	"tableswitch",
	"lookupswitch",
	"ireturn",
	"lreturn",
	"freturn",
	"dreturn",
	"areturn",
	"return",
	"getstatic",
	"putstatic",
	"getfield",
	"putfield",
	"invokevirtual",
	"invokespecial",
	"invokestatic",
	"invokeinterface",
	"invokedynamic",
	"new",
	"newarray",
	"anewarray",
	"arraylength",
	"athrow",
	"checkcast",
	"instanceof",
	"monitorenter",
	"monitorexit",
	"wide",
	"multianewarray",
	"ifnull",
	"ifnonnull",
	"goto_w",
	"jsr_w",
	"breakpoint",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"impdep1",
	"impdep2",
};

int handle_instr_unknown(bc_interpreter_t *interpreter, bool wide);
int handle_instr_nop(bc_interpreter_t *interpreter, bool wide);
int handle_instr_aconst_null(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iconst_m1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iconst_0(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iconst_1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iconst_2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iconst_3(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iconst_4(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iconst_5(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lconst_0(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lconst_1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fconst_0(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fconst_1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fconst_2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dconst_0(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dconst_1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_bipush(bc_interpreter_t *interpreter, bool wide);
int handle_instr_sipush(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ldc(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ldc_w(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ldc2_w(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iload(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lload(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fload(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dload(bc_interpreter_t *interpreter, bool wide);
int handle_instr_aload(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iload_0(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iload_1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iload_2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iload_3(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lload_0(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lload_1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lload_2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lload_3(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fload_0(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fload_1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fload_2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fload_3(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dload_0(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dload_1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dload_2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dload_3(bc_interpreter_t *interpreter, bool wide);
int handle_instr_aload_0(bc_interpreter_t *interpreter, bool wide);
int handle_instr_aload_1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_aload_2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_aload_3(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iaload(bc_interpreter_t *interpreter, bool wide);
int handle_instr_laload(bc_interpreter_t *interpreter, bool wide);
int handle_instr_faload(bc_interpreter_t *interpreter, bool wide);
int handle_instr_daload(bc_interpreter_t *interpreter, bool wide);
int handle_instr_aaload(bc_interpreter_t *interpreter, bool wide);
int handle_instr_baload(bc_interpreter_t *interpreter, bool wide);
int handle_instr_caload(bc_interpreter_t *interpreter, bool wide);
int handle_instr_saload(bc_interpreter_t *interpreter, bool wide);
int handle_instr_istore(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lstore(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fstore(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dstore(bc_interpreter_t *interpreter, bool wide);
int handle_instr_astore(bc_interpreter_t *interpreter, bool wide);
int handle_instr_istore_0(bc_interpreter_t *interpreter, bool wide);
int handle_instr_istore_1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_istore_2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_istore_3(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lstore_0(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lstore_1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lstore_2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lstore_3(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fstore_0(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fstore_1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fstore_2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fstore_3(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dstore_0(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dstore_1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dstore_2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dstore_3(bc_interpreter_t *interpreter, bool wide);
int handle_instr_astore_0(bc_interpreter_t *interpreter, bool wide);
int handle_instr_astore_1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_astore_2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_astore_3(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iastore(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lastore(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fastore(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dastore(bc_interpreter_t *interpreter, bool wide);
int handle_instr_aastore(bc_interpreter_t *interpreter, bool wide);
int handle_instr_bastore(bc_interpreter_t *interpreter, bool wide);
int handle_instr_castore(bc_interpreter_t *interpreter, bool wide);
int handle_instr_sastore(bc_interpreter_t *interpreter, bool wide);
int handle_instr_pop(bc_interpreter_t *interpreter, bool wide);
int handle_instr_pop2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dup(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dup_x1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dup_x2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dup2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dup2_x1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dup2_x2(bc_interpreter_t *interpreter, bool wide);
int handle_instr_swap(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iadd(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ladd(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fadd(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dadd(bc_interpreter_t *interpreter, bool wide);
int handle_instr_isub(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lsub(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fsub(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dsub(bc_interpreter_t *interpreter, bool wide);
int handle_instr_imul(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lmul(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fmul(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dmul(bc_interpreter_t *interpreter, bool wide);
int handle_instr_idiv(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ldiv(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fdiv(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ddiv(bc_interpreter_t *interpreter, bool wide);
int handle_instr_irem(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lrem(bc_interpreter_t *interpreter, bool wide);
int handle_instr_frem(bc_interpreter_t *interpreter, bool wide);
int handle_instr_drem(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ineg(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lneg(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fneg(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dneg(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ishl(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lshl(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ishr(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lshr(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iushr(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lushr(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iand(bc_interpreter_t *interpreter, bool wide);
int handle_instr_land(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ior(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lor(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ixor(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lxor(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iinc(bc_interpreter_t *interpreter, bool wide);
int handle_instr_i2l(bc_interpreter_t *interpreter, bool wide);
int handle_instr_i2f(bc_interpreter_t *interpreter, bool wide);
int handle_instr_i2d(bc_interpreter_t *interpreter, bool wide);
int handle_instr_l2i(bc_interpreter_t *interpreter, bool wide);
int handle_instr_l2f(bc_interpreter_t *interpreter, bool wide);
int handle_instr_l2d(bc_interpreter_t *interpreter, bool wide);
int handle_instr_f2i(bc_interpreter_t *interpreter, bool wide);
int handle_instr_f2l(bc_interpreter_t *interpreter, bool wide);
int handle_instr_f2d(bc_interpreter_t *interpreter, bool wide);
int handle_instr_d2i(bc_interpreter_t *interpreter, bool wide);
int handle_instr_d2l(bc_interpreter_t *interpreter, bool wide);
int handle_instr_d2f(bc_interpreter_t *interpreter, bool wide);
int handle_instr_i2b(bc_interpreter_t *interpreter, bool wide);
int handle_instr_i2c(bc_interpreter_t *interpreter, bool wide);
int handle_instr_i2s(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lcmp(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fcmpl(bc_interpreter_t *interpreter, bool wide);
int handle_instr_fcmpg(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dcmpl(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dcmpg(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ifeq(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ifne(bc_interpreter_t *interpreter, bool wide);
int handle_instr_iflt(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ifge(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ifgt(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ifle(bc_interpreter_t *interpreter, bool wide);
int handle_instr_if_icmpeq(bc_interpreter_t *interpreter, bool wide);
int handle_instr_if_icmpne(bc_interpreter_t *interpreter, bool wide);
int handle_instr_if_icmplt(bc_interpreter_t *interpreter, bool wide);
int handle_instr_if_icmpge(bc_interpreter_t *interpreter, bool wide);
int handle_instr_if_icmpgt(bc_interpreter_t *interpreter, bool wide);
int handle_instr_if_icmple(bc_interpreter_t *interpreter, bool wide);
int handle_instr_if_acmpeq(bc_interpreter_t *interpreter, bool wide);
int handle_instr_if_acmpne(bc_interpreter_t *interpreter, bool wide);
int handle_instr_goto(bc_interpreter_t *interpreter, bool wide);
int handle_instr_jsr(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ret(bc_interpreter_t *interpreter, bool wide);
int handle_instr_tableswitch(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lookupswitch(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ireturn(bc_interpreter_t *interpreter, bool wide);
int handle_instr_lreturn(bc_interpreter_t *interpreter, bool wide);
int handle_instr_freturn(bc_interpreter_t *interpreter, bool wide);
int handle_instr_dreturn(bc_interpreter_t *interpreter, bool wide);
int handle_instr_areturn(bc_interpreter_t *interpreter, bool wide);
int handle_instr_return(bc_interpreter_t *interpreter, bool wide);
int handle_instr_getstatic(bc_interpreter_t *interpreter, bool wide);
int handle_instr_putstatic(bc_interpreter_t *interpreter, bool wide);
int handle_instr_getfield(bc_interpreter_t *interpreter, bool wide);
int handle_instr_putfield(bc_interpreter_t *interpreter, bool wide);
int handle_instr_invokevirtual(bc_interpreter_t *interpreter, bool wide);
int handle_instr_invokespecial(bc_interpreter_t *interpreter, bool wide);
int handle_instr_invokestatic(bc_interpreter_t *interpreter, bool wide);
int handle_instr_invokeinterface(bc_interpreter_t *interpreter, bool wide);
int handle_instr_invokedynamic(bc_interpreter_t *interpreter, bool wide);
int handle_instr_new(bc_interpreter_t *interpreter, bool wide);
int handle_instr_newarray(bc_interpreter_t *interpreter, bool wide);
int handle_instr_anewarray(bc_interpreter_t *interpreter, bool wide);
int handle_instr_arraylength(bc_interpreter_t *interpreter, bool wide);
int handle_instr_athrow(bc_interpreter_t *interpreter, bool wide);
int handle_instr_checkcast(bc_interpreter_t *interpreter, bool wide);
int handle_instr_instanceof(bc_interpreter_t *interpreter, bool wide);
int handle_instr_monitorenter(bc_interpreter_t *interpreter, bool wide);
int handle_instr_monitorexit(bc_interpreter_t *interpreter, bool wide);
int handle_instr_wide(bc_interpreter_t *interpreter, bool wide);
int handle_instr_multianewarray(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ifnull(bc_interpreter_t *interpreter, bool wide);
int handle_instr_ifnonnull(bc_interpreter_t *interpreter, bool wide);
int handle_instr_goto_w(bc_interpreter_t *interpreter, bool wide);
int handle_instr_jsr_w(bc_interpreter_t *interpreter, bool wide);
int handle_instr_breakpoint(bc_interpreter_t *interpreter, bool wide);
int handle_instr_impdep1(bc_interpreter_t *interpreter, bool wide);
int handle_instr_impdep2(bc_interpreter_t *interpreter, bool wide);

static int (* const instr_table[256])(bc_interpreter_t *interpreter, bool wide) = {
	handle_instr_nop,
	handle_instr_aconst_null,
	handle_instr_iconst_m1,
	handle_instr_iconst_0,
	handle_instr_iconst_1,
	handle_instr_iconst_2,
	handle_instr_iconst_3,
	handle_instr_iconst_4,
	handle_instr_iconst_5,
	handle_instr_lconst_0,
	handle_instr_lconst_1,
	handle_instr_fconst_0,
	handle_instr_fconst_1,
	handle_instr_fconst_2,
	handle_instr_dconst_0,
	handle_instr_dconst_1,
	handle_instr_bipush,
	handle_instr_sipush,
	handle_instr_ldc,
	handle_instr_ldc_w,
	handle_instr_ldc2_w,
	handle_instr_iload,
	handle_instr_lload,
	handle_instr_fload,
	handle_instr_dload,
	handle_instr_aload,
	handle_instr_iload_0,
	handle_instr_iload_1,
	handle_instr_iload_2,
	handle_instr_iload_3,
	handle_instr_lload_0,
	handle_instr_lload_1,
	handle_instr_lload_2,
	handle_instr_lload_3,
	handle_instr_fload_0,
	handle_instr_fload_1,
	handle_instr_fload_2,
	handle_instr_fload_3,
	handle_instr_dload_0,
	handle_instr_dload_1,
	handle_instr_dload_2,
	handle_instr_dload_3,
	handle_instr_aload_0,
	handle_instr_aload_1,
	handle_instr_aload_2,
	handle_instr_aload_3,
	handle_instr_iaload,
	handle_instr_laload,
	handle_instr_faload,
	handle_instr_daload,
	handle_instr_aaload,
	handle_instr_baload,
	handle_instr_caload,
	handle_instr_saload,
	handle_instr_istore,
	handle_instr_lstore,
	handle_instr_fstore,
	handle_instr_dstore,
	handle_instr_astore,
	handle_instr_istore_0,
	handle_instr_istore_1,
	handle_instr_istore_2,
	handle_instr_istore_3,
	handle_instr_lstore_0,
	handle_instr_lstore_1,
	handle_instr_lstore_2,
	handle_instr_lstore_3,
	handle_instr_fstore_0,
	handle_instr_fstore_1,
	handle_instr_fstore_2,
	handle_instr_fstore_3,
	handle_instr_dstore_0,
	handle_instr_dstore_1,
	handle_instr_dstore_2,
	handle_instr_dstore_3,
	handle_instr_astore_0,
	handle_instr_astore_1,
	handle_instr_astore_2,
	handle_instr_astore_3,
	handle_instr_iastore,
	handle_instr_lastore,
	handle_instr_fastore,
	handle_instr_dastore,
	handle_instr_aastore,
	handle_instr_bastore,
	handle_instr_castore,
	handle_instr_sastore,
	handle_instr_pop,
	handle_instr_pop2,
	handle_instr_dup,
	handle_instr_dup_x1,
	handle_instr_dup_x2,
	handle_instr_dup2,
	handle_instr_dup2_x1,
	handle_instr_dup2_x2,
	handle_instr_swap,
	handle_instr_iadd,
	handle_instr_ladd,
	handle_instr_fadd,
	handle_instr_dadd,
	handle_instr_isub,
	handle_instr_lsub,
	handle_instr_fsub,
	handle_instr_dsub,
	handle_instr_imul,
	handle_instr_lmul,
	handle_instr_fmul,
	handle_instr_dmul,
	handle_instr_idiv,
	handle_instr_ldiv,
	handle_instr_fdiv,
	handle_instr_ddiv,
	handle_instr_irem,
	handle_instr_lrem,
	handle_instr_frem,
	handle_instr_drem,
	handle_instr_ineg,
	handle_instr_lneg,
	handle_instr_fneg,
	handle_instr_dneg,
	handle_instr_ishl,
	handle_instr_lshl,
	handle_instr_ishr,
	handle_instr_lshr,
	handle_instr_iushr,
	handle_instr_lushr,
	handle_instr_iand,
	handle_instr_land,
	handle_instr_ior,
	handle_instr_lor,
	handle_instr_ixor,
	handle_instr_lxor,
	handle_instr_iinc,
	handle_instr_i2l,
	handle_instr_i2f,
	handle_instr_i2d,
	handle_instr_l2i,
	handle_instr_l2f,
	handle_instr_l2d,
	handle_instr_f2i,
	handle_instr_f2l,
	handle_instr_f2d,
	handle_instr_d2i,
	handle_instr_d2l,
	handle_instr_d2f,
	handle_instr_i2b,
	handle_instr_i2c,
	handle_instr_i2s,
	handle_instr_lcmp,
	handle_instr_fcmpl,
	handle_instr_fcmpg,
	handle_instr_dcmpl,
	handle_instr_dcmpg,
	handle_instr_ifeq,
	handle_instr_ifne,
	handle_instr_iflt,
	handle_instr_ifge,
	handle_instr_ifgt,
	handle_instr_ifle,
	handle_instr_if_icmpeq,
	handle_instr_if_icmpne,
	handle_instr_if_icmplt,
	handle_instr_if_icmpge,
	handle_instr_if_icmpgt,
	handle_instr_if_icmple,
	handle_instr_if_acmpeq,
	handle_instr_if_acmpne,
	handle_instr_goto,
	handle_instr_jsr,
	handle_instr_ret,
	handle_instr_tableswitch,
	handle_instr_lookupswitch,
	handle_instr_ireturn,
	handle_instr_lreturn,
	handle_instr_freturn,
	handle_instr_dreturn,
	handle_instr_areturn,
	handle_instr_return,
	handle_instr_getstatic,
	handle_instr_putstatic,
	handle_instr_getfield,
	handle_instr_putfield,
	handle_instr_invokevirtual,
	handle_instr_invokespecial,
	handle_instr_invokestatic,
	handle_instr_invokeinterface,
	handle_instr_invokedynamic,
	handle_instr_new,
	handle_instr_newarray,
	handle_instr_anewarray,
	handle_instr_arraylength,
	handle_instr_athrow,
	handle_instr_checkcast,
	handle_instr_instanceof,
	handle_instr_monitorenter,
	handle_instr_monitorexit,
	handle_instr_wide,
	handle_instr_multianewarray,
	handle_instr_ifnull,
	handle_instr_ifnonnull,
	handle_instr_goto_w,
	handle_instr_jsr_w,
	handle_instr_breakpoint,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_unknown,
	handle_instr_impdep1,
	handle_instr_impdep2,
};